#!/bin/sh
# system one time tasks

PATH=/sbin:/usr/sbin:/bin:/usr/bin

echo 'Running boot scripts...'
for script in /etc/runit/boot/*; do
    [ -x "${script}" ] && "${script}"
done

touch /etc/runit/stopit
chmod 0 /etc/runit/stopit
